"""add screening tables

Revision ID: 047e90efc47b
Revises: 7ce80876e004
Create Date: 2026-08-19 10:23:29.593989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047e90efc47b'
down_revision: Union[str, Sequence[str], None] = '7ce80876e004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('result_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_id')
    )
    op.create_table('screening_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['screening_questions.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id', 'question_id', name='uq_screening_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_answers')
    op.drop_table('screenings')
    op.drop_table('screening_questions')
    # ### end Alembic commands ###
